### PR TITLE
Build Mercury cross-compiler

### PR DESCRIPTION
**Pull request by adrianwong**

### CODE REVIEW

**Comment by alfiedotwtf** [comment]
What's with the `5f1dfc806f87` filename ending?

**Comment by alfiedotwtf** [comment]
LGTM

**Comment by adrianwong** [comment]
> What's with the `5f1dfc806f87` filename ending?

It's the commit hash for the [version of `configure_cross`](https://github.com/Mercury-Language/mercury/commit/5f1dfc806f87d0d3000503f34149cddd79c15e26) that I'm using.

**Comment by alfiedotwtf** [comment]
Ah, ok cool.

**Pull request merged**
